// client/src/views/Login.vue
<template>
  <form class="container" @submit.prevent="login">
      {{error}}
      <div class="field">
            <p class="control has-icons-left has-icons-right">
                <input class="input" type="email" placeholder="Email" v-model="email">
                <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
                </span>
                <span class="icon is-small is-right">
                <i class="fas fa-check"></i>
                </span>
            </p>
        </div>
        <div class="field">
            <p class="control has-icons-left">
                <input class="input" type="password" placeholder="Password" v-model="password">
                <span class="icon is-small is-left">
                <i class="fas fa-lock"></i>
                </span>
            </p>
        </div>
        <div class="field">
            <p class="control">
                <button class="button is-success">
                Login
                </button>
            </p>
            <button class="button is-primary" @click.prevent="google_login" >
                Login with Google
            </button>
            <button class="button is-primary" @click.prevent="facebook_login" >
                Login with Facebook
            </button>
        </div>
  </form>
</template>

<script>
import {Login} from "../models/Users";
const GOOGLE_CLIENT_ID = "493198841012-b7utvcvb5ohs2jh21td1djeb51lksm07.apps.googleusercontent.com";
const FB_CLIENT_ID = "538529810199504";
let auth2 = null;

export default {
    created(){
        const googleScriptTag = document.createElement('script')
        googleScriptTag.setAttribute('src', 'https://apis.google.com/js/api:client.js')
        document.head.appendChild(googleScriptTag)
        googleScriptTag.onload = () => {
            // the global gapi variable is created by loading that script
            gapi.load('auth2', () => {
                auth2 = gapi.auth2.init({
                    client_id: GOOGLE_CLIENT_ID,
                    cookiepolicy: 'single_host_origin',
                    scope: 'profile email'
                })
            })
        }

        window.fbAsyncInit = function() {
            FB.init({
            appId      : FB_CLIENT_ID,
            cookie     : true,
            xfbml      : true,
            version    : 'v3.0'
            });
            
            //FB.AppEvents.logPageView();   
            
        };

        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

    },
    data(){
        return {
            email: '',
            password: '',
            error: '',
            profile_picture: null
        }
    },
    methods: {
        async login(){
            try {
                await Login(this.email, this.password);
                this.$router.push('/game');
            } catch (error) {
                this.error = error;
            }
        },
        google_login(){
            auth2.signIn()
            .then(googleUser =>{
                console.log(googleUser);
                
                const profile = googleUser.getBasicProfile();
                console.log("ID: " + profile.getId()); // Don't send this directly to your server!
                console.log('Full Name: ' + profile.getName());
                console.log('Given Name: ' + profile.getGivenName());
                console.log('Family Name: ' + profile.getFamilyName());
                console.log("Image URL: " + profile.getImageUrl());
                console.log("Email: " + profile.getEmail());

                this.profile_picture = profile.getImageUrl();

                return Login("google", googleUser.getAuthResponse().access_token)
                    .then(x => this.$router.push('/game'))
            } )
            .catch(error => this.error = error.error);
        },
        facebook_login(){
            FB.login(response => {
                console.log(response);

                FB.api('/me?fields=email,name,picture', response => {
                    console.log(response);
                    this.profile_picture = response.picture.data.url;
                });
                Login("facebook", response.authResponse.accessToken)
                    .then(x=> this.$router.push('/game'))
                    .catch(error => this.error = error)
                }, 
                {scope: 'email'}
            );
        }
    }
}
</script>

<style>

</style>

// react-wdym/src/views/Login.jsx
import React, { useState, useEffect } from 'react';
import {Login} from "../models/Users";
import { useHistory } from 'react-router-dom';
import {InitGoogle, InitFacebook} from '../models/oAuthHelpers';
/* globals FB*/
export default function LoginComponent(){
    
    //do this for any changeable data in React
    //these are hooks
    const [error, setError] = useState('');
    const [email, setEmail] = useState(''); 
    const [password, setPassword] = useState(''); 

    const history = useHistory();

    //similar to created() in Vue
    useEffect(() => {
        InitGoogle();
        InitFacebook();
    }, [])

    async function login(e){
        e.preventDefault();
        try {
            await Login(email, password);
            history.push('/game');
        } catch (ex) {
            setError(ex.message);
        }
    }
    function google_login(e){
        setError('You logged you in with Google');
        e.preventDefault();
        window.auth2.signIn()
            .then(googleUser =>{
                console.log(googleUser);
                
                return Login("google", googleUser.getAuthResponse().access_token)
                    .then(x => history.push('/game'))
            } )
            .catch(error => setError(error));
    }
    function facebook_login(e){
        e.preventDefault();
        FB.login(response => {
            console.log(response);

            FB.api('/me?fields=email,name,picture', response => {
                console.log(response);
                this.profile_picture = response.picture.data.url;
            });
            Login("facebook", response.authResponse.accessToken)
                .then(x=> history.push('/game'))
                .catch(error => setError(error))
            }, 
            {scope: 'email'}
        );
    }

    return(
        <form className="container" onSubmit={login}>
            {error}
            <div className="field">
                <p className="control has-icons-left has-icons-right">
                    <input className="input" type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)}/>
                    <span className="icon is-small is-left">
                    <i className="fas fa-envelope"></i>
                    </span>
                    <span className="icon is-small is-right">
                    <i className="fas fa-check"></i>
                    </span>
                </p>
            </div>
            <div className="field">
                <p className="control has-icons-left">
                    <input className="input" type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)}/>
                    <span className="icon is-small is-left">
                    <i className="fas fa-lock"></i>
                    </span>
                </p>
            </div>
            <div className="field">
                <p className="control">
                    <button className="button is-success">
                    Login
                    </button>
                </p>
                <button className="button is-primary" onClick={google_login} >
                    Login with Google
                </button>
                <button className="button is-primary" onClick={facebook_login} >
                    Login with Facebook
                </button>
            </div>
        </form>
    )
}
